### ISSUE TITLE
Zoom into the graphs of the Microsim seems broken 

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#1720]
https://github.com/PolicyEngine/policyengine-app/assets/110687043/dba22ade-d918-4672-9678-d2c71b6d6771

When double clicking to zoom out, the graph does not seem to return to the initial state

**Comment by sinano1107** [comment]
@PavelMakarchuk 
Accessing this link, it seems that the issue has been resolved.
https://policyengine.org/us/policy?focus=gov.states.ga.tax.income.credits.cdcc.rate&reform=2&region=us&timePeriod=2025&baseline=2

Are you suggesting that after zooming in, double-clicking should return to the zoomed-in screen?

**Comment by anth-volk** [comment]
@MaxGhenis For me (on Firefox), zooming in, then double-clicking to zoom out returns me to the initial frame of roughly 2000 to roughly 2038. I'd nominate to close unless anyone else is still experiencing the resetting to 2100.

**Comment by PavelMakarchuk** [comment]
I don't experience this issue anymore (Chrome)

**Comment by anth-volk** [comment]
@sinano1107 Looks like we'll be closing this out, thanks for raising.
